name: mumen_finder
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cache:
    path: ./packages/cache
  firebase_auth_repository:
    path: ./packages/firebase_auth_repository
  form_inputs:
    path: packages/form_inputs
  bloc: ^7.0.0
  equatable: ^2.0.0
  firebase_core: ^1.2.0
  flow_builder: ^0.0.2
  flutter_bloc: ^7.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  formz: ^0.4.0
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

assets:
  - /assets
  - .env
